DROP TABLE IF EXISTS profesores;
DROP TABLE IF EXISTS alumnos;
DROP TABLE IF EXISTS tareas;
DROP TABLE IF EXISTS intentos;


CREATE TABLE profesores
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	id_moodle INTEGER NULL,
	nombre_completo VARCHAR(45) NULL,
	oauth_key VARCHAR(45) NOT NULL,
	secret VARCHAR(45) NOT NULL,
	correo VARCHAR(45) NOT NULL,
	tarea_url VARCHAR(85) NULL,
	CONSTRAINT pk01_profesores PRIMARY KEY(id)
);

CREATE TABLE alumnos
(
	id INTEGER NOT NULL,
	nombre_completo VARCHAR(45) NOT NULL,
	correo VARCHAR(45) NOT NULL,
	CONSTRAINT pk01_alumnos PRIMARY KEY(id)
);

CREATE TABLE tareas
(
	id INTEGER NOT NULL,
	nombre VARCHAR(45) NOT NULL,
	url VARCHAR(85) NULL,
	num_intentos INTEGER NOT NULL,
	test TINYINT(1) NULL,
	fecha_tope DATE NOT NULL,
	CONSTRAINT pk01_tareas PRIMARY KEY(id)
);

CREATE TABLE intentos
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	tarea_id INTEGER NOT NULL,
	alumno_id INTEGER NOT NULL,
	CONSTRAINT PK01_INTENTOS PRIMARY KEY(id),
	CONSTRAINT FK01_INTENTOS FOREIGN KEY
		(tarea_id) REFERENCES tareas (id),
	CONSTRAINT FK02_INTENTOS FOREIGN KEY
		(alumno_id) REFERENCES alumnos (id)	
);